# Generated by Django 5.0.2 on 2025-11-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="logo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
