# Generated by Django 5.2.7 on 2025-11-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_companysettings_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_emailed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="parent_proforma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_tax_invoice",
                to="api.invoice",
            ),
        ),
    ]
