# Generated by Django 5.2.7 on 2025-11-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_invoice_emailed_at_invoice_is_emailed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesettings",
            name="proformaPrefix",
            field=models.CharField(default="PI-", max_length=20),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="proformaStartingNumber",
            field=models.IntegerField(default=1),
        ),
    ]
