# Generated by Django 5.2.7 on 2025-11-11 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_emailsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceFormatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_logo", models.BooleanField(default=True)),
                (
                    "logo_position",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                ("show_company_designation", models.BooleanField(default=True)),
                (
                    "company_designation_text",
                    models.CharField(default="CHARTERED ACCOUNTANT", max_length=100),
                ),
                ("header_color", models.CharField(default="#1e3a8a", max_length=7)),
                ("show_company_name", models.BooleanField(default=True)),
                ("show_trading_name", models.BooleanField(default=True)),
                ("show_address", models.BooleanField(default=True)),
                ("show_gstin", models.BooleanField(default=True)),
                ("show_pan", models.BooleanField(default=True)),
                ("show_phone", models.BooleanField(default=True)),
                ("show_email", models.BooleanField(default=True)),
                ("show_invoice_number", models.BooleanField(default=True)),
                ("show_invoice_date", models.BooleanField(default=True)),
                ("show_due_date", models.BooleanField(default=False)),
                ("show_client_gstin", models.BooleanField(default=True)),
                ("show_client_pan", models.BooleanField(default=False)),
                ("show_client_phone", models.BooleanField(default=False)),
                ("show_client_email", models.BooleanField(default=False)),
                (
                    "table_header_bg_color",
                    models.CharField(default="#1e3a8a", max_length=7),
                ),
                (
                    "table_header_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                ("show_hsn_sac_column", models.BooleanField(default=False)),
                ("show_serial_number", models.BooleanField(default=True)),
                ("show_taxable_value", models.BooleanField(default=True)),
                ("show_cgst_sgst_separate", models.BooleanField(default=True)),
                ("show_igst", models.BooleanField(default=True)),
                ("show_gst_percentage", models.BooleanField(default=False)),
                ("show_subtotal", models.BooleanField(default=True)),
                ("show_tax_breakup", models.BooleanField(default=True)),
                ("show_grand_total_in_words", models.BooleanField(default=False)),
                ("show_bank_details", models.BooleanField(default=True)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_ifsc", models.CharField(blank=True, max_length=20)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("show_signature", models.BooleanField(default=True)),
                (
                    "signature_label",
                    models.CharField(default="Authorized Signatory", max_length=100),
                ),
                ("show_company_seal", models.BooleanField(default=False)),
                ("show_payment_terms", models.BooleanField(default=True)),
                ("show_notes", models.BooleanField(default=True)),
                ("show_terms_conditions", models.BooleanField(default=True)),
                ("show_computer_generated_note", models.BooleanField(default=True)),
                ("show_page_numbers", models.BooleanField(default=True)),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_format_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Format Settings",
                "verbose_name_plural": "Invoice Format Settings",
            },
        ),
    ]
