# Generated by Django 5.2.7 on 2025-11-11 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_invoiceformatsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="rate",
        ),
    ]
