# Generated by Django 5.2.7 on 2025-11-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_paymentterm"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="api.paymentterm",
            ),
        ),
    ]
