# Generated by Django 5.0.1 on 2025-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_invoice_payment_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="stateCode",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
