# Generated by Django 5.0.1 on 2025-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_client_statecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="last_reminder_sent",
            field=models.DateTimeField(
                blank=True, help_text="Last payment reminder sent date", null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reminder_count",
            field=models.IntegerField(default=0, help_text="Number of reminders sent"),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="enablePaymentReminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="reminderEmailBody",
            field=models.TextField(
                default="Dear {client_name},\n\nThis is a friendly reminder that payment for {invoice_number} dated {invoice_date} is pending.\n\nAmount Due: ₹{total_amount}\n\nPlease make the payment at your earliest convenience.\n\nThank you!"
            ),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="reminderEmailSubject",
            field=models.CharField(
                default="Payment Reminder for Invoice {invoice_number}", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="reminderFrequencyDays",
            field=models.IntegerField(
                default=3,
                help_text="Send reminders every X days for unpaid proforma invoices",
            ),
        ),
    ]
