# Generated by Django 5.0.1 on 2025-11-19 17:18

from django.db import migrations
from django.utils.text import slugify
import uuid


def migrate_user_data_to_organizations(apps, schema_editor):
    """
    Migrate existing user-based data to organization-based multi-tenant structure.

    Strategy:
    1. Get all unique users from existing data
    2. For each user, create an Organization
    3. Create OrganizationMembership with role='owner'
    4. Update all related records to point to the new organization
    """
    User = apps.get_model('auth', 'User')
    Organization = apps.get_model('api', 'Organization')
    OrganizationMembership = apps.get_model('api', 'OrganizationMembership')
    CompanySettings = apps.get_model('api', 'CompanySettings')
    InvoiceSettings = apps.get_model('api', 'InvoiceSettings')
    Client = apps.get_model('api', 'Client')
    Invoice = apps.get_model('api', 'Invoice')
    Payment = apps.get_model('api', 'Payment')
    EmailSettings = apps.get_model('api', 'EmailSettings')
    ServiceItem = apps.get_model('api', 'ServiceItem')
    PaymentTerm = apps.get_model('api', 'PaymentTerm')
    InvoiceFormatSettings = apps.get_model('api', 'InvoiceFormatSettings')

    # Get all users that have any data
    users_with_data = set()

    # Check CompanySettings
    for cs in CompanySettings.objects.all():
        if hasattr(cs, 'user_id') and cs.user_id:
            users_with_data.add(cs.user_id)

    # Check InvoiceSettings
    for inv_s in InvoiceSettings.objects.all():
        if hasattr(inv_s, 'user_id') and inv_s.user_id:
            users_with_data.add(inv_s.user_id)

    # Check Clients
    for client in Client.objects.all():
        if hasattr(client, 'user_id') and client.user_id:
            users_with_data.add(client.user_id)

    # Check Invoices
    for invoice in Invoice.objects.all():
        if hasattr(invoice, 'user_id') and invoice.user_id:
            users_with_data.add(invoice.user_id)

    # Check Payments
    for payment in Payment.objects.all():
        if hasattr(payment, 'user_id') and payment.user_id:
            users_with_data.add(payment.user_id)

    # Check EmailSettings
    for email_s in EmailSettings.objects.all():
        if hasattr(email_s, 'user_id') and email_s.user_id:
            users_with_data.add(email_s.user_id)

    # Check ServiceItems
    for service in ServiceItem.objects.all():
        if hasattr(service, 'user_id') and service.user_id:
            users_with_data.add(service.user_id)

    # Check PaymentTerms
    for term in PaymentTerm.objects.all():
        if hasattr(term, 'user_id') and term.user_id:
            users_with_data.add(term.user_id)

    # Check InvoiceFormatSettings
    for format_s in InvoiceFormatSettings.objects.all():
        if hasattr(format_s, 'user_id') and format_s.user_id:
            users_with_data.add(format_s.user_id)

    print(f"Found {len(users_with_data)} users with existing data")

    # Create organizations and migrate data for each user
    for user_id in users_with_data:
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            print(f"Warning: User {user_id} not found, skipping...")
            continue

        # Create organization name from user details
        org_name = f"{user.get_full_name() or user.username}'s Organization"
        base_slug = slugify(org_name)
        slug = base_slug
        counter = 1

        # Ensure slug is unique
        while Organization.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        # Create the organization
        organization = Organization.objects.create(
            id=uuid.uuid4(),
            name=org_name,
            slug=slug,
            plan='free',
            is_active=True
        )

        print(f"Created organization '{org_name}' (slug: {slug}) for user {user.username}")

        # Create OrganizationMembership with owner role
        OrganizationMembership.objects.create(
            organization=organization,
            user=user,
            role='owner',
            is_active=True
        )

        # Migrate all related data
        CompanySettings.objects.filter(user_id=user_id).update(organization=organization)
        InvoiceSettings.objects.filter(user_id=user_id).update(organization=organization)
        Client.objects.filter(user_id=user_id).update(organization=organization)

        # For Invoice and Payment, also set created_by
        Invoice.objects.filter(user_id=user_id).update(
            organization=organization,
            created_by=user
        )
        Payment.objects.filter(user_id=user_id).update(
            organization=organization,
            created_by=user
        )

        EmailSettings.objects.filter(user_id=user_id).update(organization=organization)
        ServiceItem.objects.filter(user_id=user_id).update(organization=organization)
        PaymentTerm.objects.filter(user_id=user_id).update(organization=organization)
        InvoiceFormatSettings.objects.filter(user_id=user_id).update(organization=organization)

        print(f"Migrated all data for user {user.username} to organization {org_name}")

    print("Data migration completed successfully!")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - not fully implemented as it's complex.
    If you need to reverse, restore from backup.
    """
    print("Warning: Reverse migration not fully supported. Restore from backup if needed.")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_organization_remove_client_user_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_user_data_to_organizations, reverse_migration),
    ]
