# Generated by Django 5.0.1 on 2025-11-22 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_subscription_plan_coupon_models"),
    ]

    operations = []
