# Generated by Claude Code on 2025-11-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_add_client_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='gstEnabled',
            field=models.BooleanField(default=True, help_text='Enable GST calculations for invoices'),
        ),
    ]
