# Generated by Django 5.0.1 on 2025-11-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_add_subscription_upgrade_request"),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('use_tls', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Email Settings',
                'verbose_name_plural': 'System Email Settings',
            },
        ),
    ]
