# Generated by Django 4.2.7 on 2025-11-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_client_code_client_date_of_birth_and_more'),
        ('api', '0024_payment_tds_fields'),
    ]

    operations = [
    ]
