# Generated by Django 5.0.1 on 2025-11-29 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cleanup_orphan_records(apps, schema_editor):
    """
    Clean up records with NULL organization before making the field non-nullable.
    These are orphan records from incomplete data migration.
    """
    Client = apps.get_model('api', 'Client')
    Invoice = apps.get_model('api', 'Invoice')
    Payment = apps.get_model('api', 'Payment')
    CompanySettings = apps.get_model('api', 'CompanySettings')
    InvoiceSettings = apps.get_model('api', 'InvoiceSettings')
    EmailSettings = apps.get_model('api', 'EmailSettings')
    InvoiceFormatSettings = apps.get_model('api', 'InvoiceFormatSettings')
    ServiceItem = apps.get_model('api', 'ServiceItem')
    PaymentTerm = apps.get_model('api', 'PaymentTerm')

    # Delete orphan records (records without organization)
    models_to_clean = [
        Client, Invoice, Payment, CompanySettings, InvoiceSettings,
        EmailSettings, InvoiceFormatSettings, ServiceItem, PaymentTerm
    ]

    for model in models_to_clean:
        try:
            deleted_count = model.objects.filter(organization__isnull=True).delete()[0]
            if deleted_count > 0:
                print(f"Deleted {deleted_count} orphan {model.__name__} records")
        except Exception as e:
            print(f"Warning: Could not clean {model.__name__}: {e}")


def reverse_cleanup(apps, schema_editor):
    """Reverse migration - nothing to undo."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_payment_tds_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First clean up orphan records
        migrations.RunPython(cleanup_orphan_records, reverse_cleanup),
        # Rename smtp_password to _smtp_password (field name change only, same db column)
        migrations.RenameField(
            model_name="emailsettings",
            old_name="smtp_password",
            new_name="_smtp_password",
        ),
        migrations.RenameField(
            model_name="systememailsettings",
            old_name="smtp_password",
            new_name="_smtp_password",
        ),
        # Alter the field to increase max_length for encrypted values
        migrations.AlterField(
            model_name="emailsettings",
            name="_smtp_password",
            field=models.CharField(
                blank=True, db_column="smtp_password", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="systememailsettings",
            name="_smtp_password",
            field=models.CharField(
                blank=True, db_column="smtp_password", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="date_of_incorporation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="mobile",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="api.organization",
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_settings",
                to="api.organization",
            ),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_settings",
                to="api.organization",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="api.organization",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceformatsettings",
            name="company_designation_text",
            field=models.CharField(default="Professional Services", max_length=100),
        ),
        migrations.AlterField(
            model_name="invoiceformatsettings",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_format_settings",
                to="api.organization",
            ),
        ),
        migrations.AlterField(
            model_name="invoicesettings",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_settings",
                to="api.organization",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="api.organization",
            ),
        ),
        migrations.AlterField(
            model_name="paymentterm",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_terms",
                to="api.organization",
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_items",
                to="api.organization",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='["Feature 1", "Feature 2", "Feature 3"]',
            ),
        ),
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the requesting user (preserved even after user deletion)",
                        max_length=254,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="User-provided reason for deletion"
                    ),
                ),
                (
                    "data_types_requested",
                    models.JSONField(
                        default=list, help_text="Types of data requested for deletion"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason if request was rejected"
                    ),
                ),
                (
                    "legal_hold",
                    models.BooleanField(
                        default=False,
                        help_text="Data under legal hold cannot be deleted",
                    ),
                ),
                (
                    "retention_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when data can be deleted (if under retention)",
                        null=True,
                    ),
                ),
                ("verification_token", models.CharField(blank=True, max_length=100)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_requests",
                        to="api.organization",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Deletion Request",
                "verbose_name_plural": "Data Deletion Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FailedLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email attempted for login",
                        max_length=254,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "failure_reason",
                    models.CharField(default="invalid_credentials", max_length=100),
                ),
                (
                    "attempt_count",
                    models.IntegerField(
                        default=1, help_text="Consecutive failed attempts"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Account locked until this time",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Failed Login Attempt",
                "verbose_name_plural": "Failed Login Attempts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="api_failedl_email_495e14_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="api_failedl_ip_addr_552727_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("login_failed", "Failed Login Attempt"),
                            ("password_change", "Password Changed"),
                            ("password_reset", "Password Reset"),
                            ("profile_update", "Profile Updated"),
                            ("create", "Record Created"),
                            ("update", "Record Updated"),
                            ("delete", "Record Deleted"),
                            ("view", "Record Viewed"),
                            ("export", "Data Exported"),
                            ("email_sent", "Email Sent"),
                            ("payment_recorded", "Payment Recorded"),
                            ("invoice_generated", "Invoice Generated"),
                            ("consent_given", "Consent Given"),
                            ("consent_withdrawn", "Consent Withdrawn"),
                            ("data_deletion", "Data Deletion Request"),
                            ("data_export", "Personal Data Export"),
                            ("api_access", "API Access"),
                            ("settings_change", "Settings Changed"),
                            ("permission_change", "Permission Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the action"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Model/Resource type affected (e.g., Invoice, Client)",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the affected resource",
                        max_length=100,
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(
                        blank=True,
                        help_text="Name/identifier of the affected resource",
                        max_length=255,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser/Client user agent string"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        help_text="HTTP method (GET, POST, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, help_text="API endpoint/URL path", max_length=500
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, help_text="Previous values before change", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="New values after change", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional context data", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="api.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="api_auditlo_user_id_b608a1_idx",
                    ),
                    models.Index(
                        fields=["organization", "created_at"],
                        name="api_auditlo_organiz_4f46f2_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="api_auditlo_action_e69819_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="api_auditlo_resourc_c074b3_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="api_auditlo_ip_addr_5903d9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("terms_of_service", "Terms of Service"),
                            ("privacy_policy", "Privacy Policy"),
                            ("data_processing", "Data Processing"),
                            ("marketing_emails", "Marketing Emails"),
                            ("analytics", "Analytics & Tracking"),
                            ("third_party_sharing", "Third Party Data Sharing"),
                            ("payment_processing", "Payment Processing"),
                            ("invoice_storage", "Invoice Data Storage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("consent_given", models.BooleanField(default=False)),
                (
                    "consent_text",
                    models.TextField(help_text="The exact text user consented to"),
                ),
                (
                    "policy_version",
                    models.CharField(
                        help_text="Version of the policy/terms", max_length=20
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "collection_method",
                    models.CharField(
                        default="web_form",
                        help_text="How consent was collected",
                        max_length=50,
                    ),
                ),
                (
                    "consented_at",
                    models.DateTimeField(
                        blank=True, help_text="When consent was given", null=True
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, help_text="When consent was withdrawn", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Consent expiry date (if applicable)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consents",
                        to="api.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Consent",
                "verbose_name_plural": "User Consents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type"],
                        name="api_usercon_user_id_62f0c2_idx",
                    ),
                    models.Index(
                        fields=["consent_given"], name="api_usercon_consent_90d7c7_idx"
                    ),
                ],
                "unique_together": {("user", "consent_type", "policy_version")},
            },
        ),
    ]
