# Generated by Django 4.2.7 on 2025-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20251126_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceformatsettings',
            name='company_designation_text',
            field=models.CharField(default='Professional Services', max_length=100),
        ),
    ]
