# Generated by Django 4.2.7 on 2025-11-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_compliance_models'),
        ('api', '0026_alter_invoiceformatsettings_company_designation_text'),
    ]

    operations = [
    ]
