# Generated by Django 5.0.1 on 2025-12-01 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_merge_20251129_1912"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkEmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Campaign name for reference", max_length=255
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(help_text="Email body - supports HTML")),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("all_users", "All Users"),
                            ("all_admins", "All Organization Admins/Owners"),
                            ("specific_plan", "Users on Specific Plan"),
                            ("active_users", "Active Users Only"),
                            ("inactive_users", "Inactive Users Only"),
                            ("custom", "Custom Selection"),
                        ],
                        default="all_users",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="When to send the email", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_email_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="If recipient_type is specific_plan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Email Campaign",
                "verbose_name_plural": "Bulk Email Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkEmailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("user_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="api.bulkemailcampaign",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Email Recipient",
                "verbose_name_plural": "Bulk Email Recipients",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for reference", max_length=255
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("announcement", "General Announcement"),
                            ("plan_change", "Plan/Pricing Change"),
                            ("new_feature", "New Feature"),
                            ("maintenance", "Scheduled Maintenance"),
                            ("security", "Security Update"),
                            ("policy_update", "Policy Update"),
                            ("custom", "Custom"),
                        ],
                        default="announcement",
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(help_text="Email body - supports HTML")),
                (
                    "available_placeholders",
                    models.TextField(
                        blank=True,
                        default="{{user_name}}, {{organization_name}}, {{email}}",
                        help_text="Available placeholders that can be used in the template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_email_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Email Template",
                "verbose_name_plural": "Bulk Email Templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bulkemailcampaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="api.bulkemailtemplate",
            ),
        ),
    ]
