# Generated by Django 5.0.1 on 2025-12-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_add_bulk_email_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("otp_code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email OTP",
                "verbose_name_plural": "Email OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "otp_code"],
                        name="api_emailot_email_34408e_idx",
                    ),
                    models.Index(
                        fields=["email", "is_verified"],
                        name="api_emailot_email_067663_idx",
                    ),
                ],
            },
        ),
    ]
