# Generated by Django 5.0.1 on 2025-12-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_add_email_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gst_tds_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="GST TDS deducted amount (for Govt undertakings)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="gst_tds_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="GST TDS deducted amount (for Govt undertakings)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="tds_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Income Tax TDS deducted amount",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="tds_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Income Tax TDS deducted amount",
                max_digits=12,
            ),
        ),
    ]
