# Generated by Django 5.0.1 on 2025-12-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_add_gst_tds_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="discount_days",
            field=models.IntegerField(
                blank=True,
                help_text="Additional days to add to subscription",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_fixed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed amount discount in rupees",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage discount (e.g., 20 for 20%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of discount types: percentage, fixed, extended_period",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("percentage", "Percentage Discount"),
                    ("fixed", "Fixed Amount Discount"),
                    ("extended_period", "Extended Period"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Legacy field - 20 for 20%, 500 for ₹500, 30 for 30 days",
                max_digits=10,
                null=True,
            ),
        ),
    ]
