# Generated by Django 5.0.1 on 2025-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_add_multiple_discount_types_to_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_organizations",
            field=models.IntegerField(
                default=1, help_text="Maximum organizations allowed"
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("viewer", "Viewer"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
