# Generated by Django 5.0.1 on 2025-12-06 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_add_max_organizations_to_subscription_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TallyMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tally_host", models.CharField(default="localhost", max_length=255)),
                ("tally_port", models.IntegerField(default=9000)),
                ("sales_ledger", models.CharField(default="Sales", max_length=255)),
                ("cgst_ledger", models.CharField(default="CGST", max_length=255)),
                ("sgst_ledger", models.CharField(default="SGST", max_length=255)),
                ("igst_ledger", models.CharField(default="IGST", max_length=255)),
                (
                    "round_off_ledger",
                    models.CharField(blank=True, default="Round Off", max_length=255),
                ),
                (
                    "discount_ledger",
                    models.CharField(
                        blank=True, default="Discount Allowed", max_length=255
                    ),
                ),
                (
                    "default_party_group",
                    models.CharField(default="Sundry Debtors", max_length=255),
                ),
                ("tally_company_name", models.CharField(blank=True, max_length=255)),
                ("tally_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tally_mapping",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tally Mapping",
                "verbose_name_plural": "Tally Mappings",
            },
        ),
        migrations.CreateModel(
            name="TallySyncHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of invoice period synced"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="End date of invoice period synced"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("invoices_synced", models.IntegerField(default=0)),
                ("invoices_failed", models.IntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("error_message", models.TextField(blank=True)),
                ("failed_invoice_ids", models.JSONField(blank=True, default=list)),
                (
                    "tally_response",
                    models.TextField(blank=True, help_text="Raw response from Tally"),
                ),
                ("sync_started_at", models.DateTimeField(auto_now_add=True)),
                ("sync_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tally_sync_history",
                        to="api.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tally_syncs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tally Sync History",
                "verbose_name_plural": "Tally Sync Histories",
                "ordering": ["-sync_started_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTallySync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced", models.BooleanField(default=True)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                ("tally_voucher_number", models.CharField(blank=True, max_length=100)),
                ("tally_voucher_date", models.DateField(blank=True, null=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tally_sync",
                        to="api.invoice",
                    ),
                ),
                (
                    "sync_history",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_syncs",
                        to="api.tallysynchistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Tally Sync",
                "verbose_name_plural": "Invoice Tally Syncs",
            },
        ),
    ]
