# Generated by Django 5.0.1 on 2025-12-06 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_tally_sync_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Name for this scheduled invoice (e.g., "Monthly Retainer - ABC Corp")',
                        max_length=255,
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("proforma", "Proforma Invoice"),
                            ("tax", "Tax Invoice"),
                        ],
                        default="proforma",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        default=1, help_text="Day of month for monthly/yearly (1-28)"
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week for weekly",
                        null=True,
                    ),
                ),
                (
                    "month_of_year",
                    models.IntegerField(
                        blank=True, help_text="Month for yearly (1-12)", null=True
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date for scheduled invoices"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="End date (leave blank for indefinite)",
                        null=True,
                    ),
                ),
                (
                    "max_occurrences",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of invoices to generate (leave blank for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes to include on generated invoices"
                    ),
                ),
                (
                    "auto_send_email",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically email invoice to client after generation",
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True,
                        help_text="Custom email subject (leave blank for default)",
                        max_length=255,
                    ),
                ),
                (
                    "email_body",
                    models.TextField(
                        blank=True,
                        help_text="Custom email body (leave blank for default)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "occurrences_generated",
                    models.IntegerField(
                        default=0, help_text="Number of invoices generated so far"
                    ),
                ),
                (
                    "last_generated_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last generated invoice",
                        null=True,
                    ),
                ),
                (
                    "next_generation_date",
                    models.DateField(
                        blank=True,
                        help_text="Next scheduled generation date",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_invoices",
                        to="api.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scheduled_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_invoices",
                        to="api.organization",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_invoices",
                        to="api.paymentterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Invoice",
                "verbose_name_plural": "Scheduled Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("hsn_sac", models.CharField(blank=True, max_length=50)),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scheduled_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.scheduledinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Invoice Item",
                "verbose_name_plural": "Scheduled Invoice Items",
            },
        ),
        migrations.CreateModel(
            name="ScheduledInvoiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("email_failed", "Invoice Created, Email Failed"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("generation_date", models.DateField()),
                ("error_message", models.TextField(blank=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_log",
                        to="api.invoice",
                    ),
                ),
                (
                    "scheduled_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_logs",
                        to="api.scheduledinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Invoice Log",
                "verbose_name_plural": "Scheduled Invoice Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
