# Generated by Django 5.0.1 on 2025-12-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_user_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cgst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total CGST amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="igst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total IGST amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_interstate",
            field=models.BooleanField(
                default=False,
                help_text="True if interstate (IGST), False if local (CGST+SGST)",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sgst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total SGST amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="cgst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="CGST amount for this item",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="igst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="IGST amount for this item",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="sgst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="SGST amount for this item",
                max_digits=12,
            ),
        ),
    ]
