# Generated by Django 5.0.1 on 2025-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_add_gst_breakdown_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="data_protected",
            field=models.BooleanField(
                default=True,
                help_text="User data is protected and cannot be deleted without superadmin permission",
            ),
        ),
        migrations.AlterField(
            model_name="invoicesettings",
            name="reminderEmailBody",
            field=models.TextField(
                default="Dear {client_name},\n\nThis is a friendly reminder that payment for {invoice_number} dated {invoice_date} is pending.\n\nAmount Due: Rs. {total_amount}\n\nPlease make the payment at your earliest convenience.\n\nThank you!"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(
                default=False, help_text="Auto-renewal is not currently implemented"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("active", "Active"),
                    ("grace_period", "Grace Period"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
