# Generated by Django 5.0.1 on 2025-12-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_gst_breakdown_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='reminderEmailBody',
            field=models.TextField(default='Dear {client_name},\n\nThis is a friendly reminder that payment for {invoice_number} dated {invoice_date} is pending.\n\nAmount Due: Rs. {total_amount}\n\nPlease make the payment at your earliest convenience.\n\nThank you!'),
        ),
    ]
