# Generated by Django 5.0.1 on 2025-12-18 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_add_grace_period_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        help_text="Name of account holder", max_length=255
                    ),
                ),
                (
                    "account_number",
                    models.CharField(help_text="Bank account number", max_length=50),
                ),
                (
                    "bank_name",
                    models.CharField(help_text="Name of the bank", max_length=255),
                ),
                (
                    "branch_name",
                    models.CharField(
                        blank=True, help_text="Branch name", max_length=255
                    ),
                ),
                ("ifsc_code", models.CharField(help_text="IFSC code", max_length=20)),
                (
                    "upi_id",
                    models.CharField(
                        blank=True, help_text="UPI ID for payments", max_length=100
                    ),
                ),
                (
                    "upi_qr_code",
                    models.TextField(
                        blank=True, help_text="Base64 encoded QR code image"
                    ),
                ),
                (
                    "payment_instructions",
                    models.TextField(
                        blank=True, help_text="Additional instructions for payment"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Settings",
                "verbose_name_plural": "Payment Settings",
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount to be paid", max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount applied",
                        max_digits=10,
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final amount after discount",
                        max_digits=10,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(help_text="UTR/Transaction ID", max_length=200),
                ),
                ("payment_date", models.DateField(help_text="Date of payment")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer (NEFT/RTGS/IMPS)"),
                            ("upi", "UPI"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash Deposit"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=50,
                    ),
                ),
                (
                    "payment_screenshot",
                    models.TextField(
                        blank=True, help_text="Base64 encoded payment screenshot"
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes from user"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Notes from admin"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection"),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_requests",
                        to="api.coupon",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_requests",
                        to="api.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to="api.subscriptionplan",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_request",
                        to="api.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Request",
                "verbose_name_plural": "Payment Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
