# Generated by Django 5.0.1 on 2025-12-18 19:14

from django.db import migrations


def seed_payment_settings(apps, schema_editor):
    """Seed initial payment settings with company bank details"""
    PaymentSettings = apps.get_model('api', 'PaymentSettings')

    # Only create if no settings exist
    if not PaymentSettings.objects.exists():
        PaymentSettings.objects.create(
            account_holder_name='Chinmay Technosoft Private Limited',
            account_number='50200092327034',
            bank_name='HDFC Bank',
            branch_name='Navrangpura',
            ifsc_code='HDFC0000006',
            upi_id='',
            upi_qr_code='',
            payment_instructions='Please mention your Organization Name in the payment reference/remarks.',
            is_active=True,
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded payment settings"""
    PaymentSettings = apps.get_model('api', 'PaymentSettings')
    PaymentSettings.objects.filter(
        account_holder_name='Chinmay Technosoft Private Limited',
        account_number='50200092327034'
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_add_payment_settings_and_requests"),
    ]

    operations = [
        migrations.RunPython(seed_payment_settings, reverse_seed),
    ]
