# Generated by Django 5.0.1 on 2025-12-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_invoicesettings_reminderemailbody'),
        ('api', '0039_seed_payment_settings'),
    ]

    operations = [
    ]
