# Generated by Django 5.0.1 on 2025-12-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_add_review_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("otp_code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether password has been reset"
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Password Reset OTP",
                "verbose_name_plural": "Password Reset OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "otp_code"],
                        name="api_passwor_email_5c0f4b_idx",
                    ),
                    models.Index(
                        fields=["email", "is_verified"],
                        name="api_passwor_email_9a77c9_idx",
                    ),
                ],
            },
        ),
    ]
