# Generated by Django 5.0.1 on 2025-12-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_add_review_models'),
        ('api', '0040_merge_20251218_1958'),
    ]

    operations = [
    ]
