# Generated by Django 5.0.1 on 2025-12-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_merge_0040_add_review_models_0040_merge_20251218_1958'),
        ('api', '0041_password_reset_otp'),
    ]

    operations = [
    ]
