# Generated by Django 5.0.1 on 2026-01-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_add_session_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceformatsettings",
            name="show_quantity_column",
            field=models.BooleanField(
                default=False, help_text="Show quantity column in invoice items"
            ),
        ),
        migrations.AddField(
            model_name="invoiceformatsettings",
            name="show_rate_column",
            field=models.BooleanField(
                default=False, help_text="Show rate/unit price column in invoice items"
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantity of items/units",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rate per unit",
                max_digits=12,
                null=True,
            ),
        ),
    ]
