# Generated by Django 5.0.1 on 2026-01-12 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_add_staff_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="acquired_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Sales person who acquired this tenant (only for sales source)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acquired_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="acquisition_campaign",
            field=models.CharField(
                blank=True,
                help_text="Campaign name for advertisement tracking (e.g., Google Ads Jan 2026)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="acquisition_coupon",
            field=models.ForeignKey(
                blank=True,
                help_text="Coupon used during acquisition (for coupon/advertisement source)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acquired_organizations",
                to="api.coupon",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="acquisition_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the tenant was acquired (defaults to created_at date)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="acquisition_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about acquisition"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="acquisition_source",
            field=models.CharField(
                choices=[
                    ("organic", "Direct/Organic"),
                    ("sales", "Sales Team"),
                    ("advertisement", "Advertisement"),
                    ("referral", "Referral"),
                    ("partner", "Partner"),
                    ("coupon", "Coupon Campaign"),
                    ("other", "Other"),
                ],
                default="organic",
                help_text="How this tenant was acquired",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that referred this tenant (for referral source)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="api.organization",
            ),
        ),
    ]
