# Generated by Django 5.0.1 on 2026-01-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_add_organization_acquisition_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="campaign_name",
            field=models.CharField(
                blank=True,
                help_text="Campaign name for attribution (e.g., 'Google Ads Jan 2026')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="campaign_source",
            field=models.CharField(
                blank=True,
                help_text="Campaign source (e.g., 'google', 'facebook', 'instagram')",
                max_length=100,
            ),
        ),
    ]
