# Generated by Django 5.0.1 on 2026-01-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_add_coupon_campaign_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicesettings",
            name="reminderEmailBody",
            field=models.TextField(
                default="Dear {client_name},\n\nThis is a friendly reminder regarding Invoice {invoice_number} dated {invoice_date}.\n\nInvoice Total: Rs. {total_amount}\nAmount Paid: Rs. {paid_amount}\nBalance Due: Rs. {pending_amount}\n\nPlease make the payment of Rs. {pending_amount} at your earliest convenience.\n\nThank you for your business!\n\nNote: This is reminder #{reminder_count}."
            ),
        ),
        migrations.AlterField(
            model_name="invoicesettings",
            name="reminderEmailSubject",
            field=models.CharField(
                default="Payment Reminder for Invoice {invoice_number} - Balance: Rs. {pending_amount}",
                max_length=255,
            ),
        ),
    ]
