# Generated by Django 5.0.1 on 2026-01-18 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_add_tally_invoice_series_mapping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tallymapping",
            name="auto_detect_series",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tallymapping",
            name="detected_tally_prefix",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="tallymapping",
            name="invoice_number_mode",
            field=models.CharField(
                choices=[
                    ("keep", "Keep Tally Number"),
                    ("nexinvo", "Use NexInvo Series"),
                    ("custom", "Custom Prefix"),
                ],
                default="keep",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tallymapping",
            name="tally_invoice_prefix",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.CreateModel(
            name="ExpensePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Expense"),
                            ("salary", "Salary/Wages"),
                            ("rent", "Rent"),
                            ("utilities", "Utilities (Electricity, Water, etc.)"),
                            ("office", "Office Supplies"),
                            ("travel", "Travel & Conveyance"),
                            ("professional", "Professional Fees"),
                            ("maintenance", "Repair & Maintenance"),
                            ("communication", "Communication (Phone, Internet)"),
                            ("insurance", "Insurance"),
                            ("taxes", "Taxes & Duties"),
                            ("bank_charges", "Bank Charges"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "payee_name",
                    models.CharField(
                        help_text="Who was the payment made to?", max_length=200
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Transaction/Cheque/Receipt No.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Brief description of this payment", max_length=500
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expense_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_payments",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Payment",
                "verbose_name_plural": "Expense Payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
