# Generated by Django 5.0.1 on 2026-01-19 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_expense_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "nature",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("sequence", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_groups",
                        to="api.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.accountgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Group",
                "verbose_name_plural": "Account Groups",
                "ordering": ["sequence", "name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_code", models.CharField(blank=True, max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("alias", models.CharField(blank=True, max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("bank", "Bank Account"),
                            ("cash", "Cash Account"),
                            ("debtor", "Sundry Debtor"),
                            ("creditor", "Sundry Creditor"),
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Capital/Equity"),
                            ("tax", "Tax Account"),
                            ("stock", "Stock/Inventory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "opening_balance_type",
                    models.CharField(
                        choices=[("Dr", "Debit"), ("Cr", "Credit")],
                        default="Dr",
                        max_length=2,
                    ),
                ),
                ("opening_balance_date", models.DateField(blank=True, null=True)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "current_balance_type",
                    models.CharField(
                        choices=[("Dr", "Debit"), ("Cr", "Credit")],
                        default="Dr",
                        max_length=2,
                    ),
                ),
                ("is_bank_account", models.BooleanField(default=False)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("ifsc_code", models.CharField(blank=True, max_length=20)),
                ("branch", models.CharField(blank=True, max_length=100)),
                ("gst_applicable", models.BooleanField(default=False)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("gst_registration_type", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system_account", models.BooleanField(default=False)),
                ("allow_negative_balance", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="api.accountgroup",
                    ),
                ),
                (
                    "linked_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_account",
                        to="api.client",
                    ),
                ),
                (
                    "linked_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_account",
                        to="api.supplier",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_accounts",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Account",
                "verbose_name_plural": "Ledger Accounts",
                "ordering": ["group__sequence", "name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reconciliation_date", models.DateField()),
                ("statement_date", models.DateField()),
                (
                    "statement_opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "statement_closing_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("book_balance", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "reconciled_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "unreconciled_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "unreconciled_debits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_reconciliations",
                        to="api.organization",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="api.ledgeraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Reconciliation",
                "verbose_name_plural": "Bank Reconciliations",
                "ordering": ["-reconciliation_date"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("purchase", "Purchase"),
                            ("receipt", "Receipt"),
                            ("payment", "Payment"),
                            ("contra", "Contra"),
                            ("journal", "Journal"),
                            ("debit_note", "Debit Note"),
                            ("credit_note", "Credit Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("voucher_number", models.CharField(max_length=50)),
                ("voucher_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("narration", models.TextField(blank=True)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("reference_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="posted",
                        max_length=20,
                    ),
                ),
                ("synced_to_tally", models.BooleanField(default=False)),
                ("tally_voucher_number", models.CharField(blank=True, max_length=50)),
                ("tally_sync_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers",
                        to="api.expensepayment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers",
                        to="api.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="api.organization",
                    ),
                ),
                (
                    "party_ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="party_vouchers",
                        to="api.ledgeraccount",
                    ),
                ),
                (
                    "payment_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers",
                        to="api.payment",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers",
                        to="api.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher",
                "verbose_name_plural": "Vouchers",
                "ordering": ["-voucher_date", "-created_at"],
                "unique_together": {("organization", "voucher_type", "voucher_number")},
            },
        ),
        migrations.CreateModel(
            name="VoucherEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("bill_reference", models.CharField(blank=True, max_length=100)),
                ("bill_date", models.DateField(blank=True, null=True)),
                ("bill_type", models.CharField(blank=True, max_length=20)),
                ("particulars", models.CharField(blank=True, max_length=500)),
                ("sequence", models.IntegerField(default=0)),
                (
                    "ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voucher_entries",
                        to="api.ledgeraccount",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="api.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher Entry",
                "verbose_name_plural": "Voucher Entries",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("description", models.CharField(max_length=500)),
                (
                    "debit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("bank_reference", models.CharField(blank=True, max_length=100)),
                ("bank_date", models.DateField(blank=True, null=True)),
                ("is_reconciled", models.BooleanField(default=False)),
                ("reconciled_date", models.DateField(blank=True, null=True)),
                ("is_bank_only", models.BooleanField(default=False)),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.bankreconciliation",
                    ),
                ),
                (
                    "voucher_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_items",
                        to="api.voucherentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Reconciliation Item",
                "verbose_name_plural": "Bank Reconciliation Items",
                "ordering": ["transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("books_beginning_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_years",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Year",
                "verbose_name_plural": "Financial Years",
                "ordering": ["-start_date"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="VoucherNumberSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_type", models.CharField(max_length=20)),
                ("prefix", models.CharField(default="", max_length=20)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                ("starting_number", models.IntegerField(default=1)),
                ("current_number", models.IntegerField(default=0)),
                ("financial_year", models.CharField(max_length=10)),
                ("number_width", models.IntegerField(default=4)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_number_series",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher Number Series",
                "verbose_name_plural": "Voucher Number Series",
                "unique_together": {("organization", "voucher_type", "financial_year")},
            },
        ),
    ]
