# Generated by Django 5.0.1 on 2026-02-11 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_accountgroup_ledgeraccount_bankreconciliation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="post_to_ledger",
            field=models.BooleanField(
                default=True, help_text="Auto-post accounting entry to ledger on save"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("services", "Service Provider"),
                    ("goods", "Goods Trader"),
                    ("both", "Both Services & Goods"),
                ],
                default="both",
                help_text="Type of business: Service Provider, Goods Trader, or Both",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "status"], name="idx_invoice_org_status"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "invoice_type"], name="idx_invoice_org_type"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "invoice_date"], name="idx_invoice_org_date"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "client"], name="idx_invoice_org_client"
            ),
        ),
    ]
