# Generated by Django 5.0.1 on 2026-02-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_add_post_to_ledger_to_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="tallymapping",
            name="last_realtime_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tallymapping",
            name="realtime_sync_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tallymapping",
            name="realtime_sync_interval",
            field=models.IntegerField(
                default=60, help_text="Sync interval in seconds (30-300)"
            ),
        ),
        migrations.AddField(
            model_name="tallymapping",
            name="realtime_sync_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Last known Tally state for change detection",
            ),
        ),
        migrations.AddField(
            model_name="tallymapping",
            name="realtime_sync_voucher_types",
            field=models.JSONField(
                blank=True, default=list, help_text="Voucher types to sync"
            ),
        ),
        migrations.CreateModel(
            name="TallyPendingSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_type", models.CharField(max_length=20)),
                ("record_id", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        default="create",
                        max_length=10,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Serialized record data for Tally"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tally_pending_syncs",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tally Pending Sync",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TallyRealtimeSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tally_to_nexinvo", "Tally → NexInvo"),
                            ("nexinvo_to_tally", "NexInvo → Tally"),
                            ("sync_started", "Sync Started"),
                            ("sync_stopped", "Sync Stopped"),
                            ("error", "Error"),
                            ("conflict", "Conflict"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tally_realtime_sync_logs",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tally Realtime Sync Log",
                "ordering": ["-created_at"],
            },
        ),
    ]
